[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"

[rpc_endpoints]
mantle_sepolia = "${MANTLE_SEPOLIA_RPC_URL:-https://rpc.sepolia.mantle.xyz}"
avalanche = "${AVALANCHE_RPC_URL:-https://api.avax.network/ext/bc/C/rpc}"
fuji = "${FUJI_RPC_URL:-https://api.avax-test.network/ext/bc/C/rpc}"

[etherscan]
mantle_sepolia = { key = "${MANTLE_API_KEY:-}" }
avalanche = { key = "${SNOWTRACE_API_KEY:-}" }
fuji = { key = "${SNOWTRACE_API_KEY:-}" }
